/**
*	File Name 	: server/modules/game
*	Description	: this module holds all game operations
*	Author		: kadoshms
*/

var winston 		= 	require('winston');

/**
 * Construct a new game manager
 * @param {socket.io} io object
 * @param {object} card map generated by server
 */
function Game(io, map)
{
	game = this;
	this.io = io;
	this.map = map;
}

/**
 * Hit player
 * @param {pobject} params parameters
 */
Game.prototype.hit = function(params){
	var card = params.room.getDeck().draw();
	winston.log('info', 'player '+params.player.id+' drawed card '+ card + " and value " + game.map[card].value);

	params.player.handCards(card);

	return card;
}

module.exports = Game;